### ISSUE TITLE
BBB not working

### ISSUE THREAD

**Issue by Vozf** [leon-w/panopto-dl#14]
https://balancer.bbb.rbg.tum.de/playback/presentation/2.3/e789236f98b21cb1b0c658d2f7039d2bdb812a84-1714478796617
For this video extension doesn't create the dl command

**Comment by leon-w** [comment]
The issue has been resolved (problem with the webpack configuration).

Please note that for the given example video, you can only dowload the webcam stream, not the screen itself. This is due to the fact that the screen is not a video stream but rendered dynamically in the browser based on screenshots and SVG annotations so it's not trivial to download. A while back i worked on a python project to locally render BBB videos and almost completed it but never really finalized it. If you are interested in finishing it, let me know!

**Comment by Vozf** [comment]
Thanks for the fix
